### ISSUE TITLE
error run

### ISSUE THREAD

**Issue by kinzinho666** [jundycosmod/yii2-simple-app-with-rbac#10]
The file or directory to be published does not exist: C:\xampp\htdocs\sistema5\vendor\bower/jquery/dist

 in C:\xampp\htdocs\sistema5\vendor\yiisoft\yii2\web\AssetManager.phpat line 456

**Comment by jundycosmod** [comment]
@kinzinho666 , thank you for reporting this issue. I might have overlooked this few years back, but this is really a great skeleton for any back-office maintenance app.
